swagger: '2.0'
info:
  title: Reciclando
  version: 1.0.0
produces:
  - application/json
externalDocs:
  description: "Reciclando Invision"
  url: "https://projects.invisionapp.com/share/5RNT0ZQQUPM#/screens"
tags:
  - "Users"
  - "Bales"
  - "Containers"
  - "Collections"
  - "Routes"
  - "Classification"
  - "Events"

paths:
  /organizations/login:
    post:
      tags:
        - "Organizations"
      operationId: organizationLogin
      summary: Organization login.
      parameters:
        - in: body
          name: name
          required: true
          type: string
        - in: body
          name: password
          required: true
          type: string
        - in: header
          name: deviceIdHeader
          type: string
        - in: header
          name: deviceTypeHeader
          type: string
          enum: ['SmartPhone', 'Tablet']
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Organization'
          headers:
            ApiKey:
              type: string
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Organization not found by the given name.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'

  /organizations/{organization_id}/users:
    get:
      tags:
        - "Users"
      operationId: getUsersFromOrganization
      summary: List users from an organization.
      parameters:
        - in: path
          name: organization_id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: An organization with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /organizations/{organization_id}/users/{id}:
    get:
      tags:
        - "Users"
      operationId: getAUserFromAnOrganization
      summary: Get one user from an organization.
      parameters:
        - in: path
          name: organization_id
          required: true
          type: integer
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: An organization or user with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /organizations/{organization_id}/users/{id}/login:
    post:
      tags:
        - "Users"
      operationId: userEnterSystem
      summary: User enter to the app.
      parameters:
        - in: path
          name: organization_id
          required: true
          type: integer
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: An organization or user with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKey: []

  /bales:
    get:
      tags:
        - "Bales"
      operationId: getBales
      summary: List bales from logged organization.
      parameters:
        - in: query
          name: material
          required: false
          type: string
          enum: ['Trash', 'Glass', 'Plastic']
        - in: query
          name: init_date
          required: false
          type: string
          format: date
        - in: query
          name: end_date
          required: false
          type: string
          format: date
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Bale'
          headers:
            Link:
              schema:
                type: string
              description: gives the information of last, next, previous or first page.
            Per-page:
              schema:
                type: integer
              description: gives information of the number of records per page.
            Total:
              schema:
                type: integer
              description: gives the number of records in total.
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKey: []

  /bales/{bale_id}:
    get:
      tags:
        - "Bales"
      operationId: getBale
      summary: Get one bale from logged organization.
      parameters:
        - in: path
          name: bale_id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Bale'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A bale with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

    post:
      tags:
        - "Bales"
      operationId: createBale
      summary: Create a bale belonging to logged organization.
      parameters:
        - in: body
          name: bale
          schema:
            $ref: '#/definitions/Bale'
      responses:
        200:
          description: OK
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

    put:
      tags:
        - "Bales"
      operationId: updateBale
      summary: Update a bale from logged organization.
      parameters:
        - in: path
          name: bale_id
          required: true
          type: integer
        - in: body
          name: bale
          schema:
            $ref: '#/definitions/Bale'
      responses:
        200:
          description: OK
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A bale with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /pockets:
    get:
      tags:
        - "Pockets"
      operationId: getUnclassifiedPockets
      summary: List unclassified and checked-in pockets from logged organization.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/UnclassifiedPocket'
          headers:
            Link:
              schema:
                type: string
              description: gives the information of last, next, previous or first page.
            Per-page:
              schema:
                type: integer
              description: gives information of the number of records per page.
            Total:
              schema:
                type: integer
              description: gives the number of records in total.
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /pockets/{pocket_id}/add_weight:
    put:
      tags:
        - "Pockets"
      operationId: addWeight
      summary: Add the weight of unweighed pockets from logged organization.
      parameters:
        - in: path
          name: pocket_id
          required: true
          type: integer
        - in: body
          name: weight
          required: true
          type: float
      responses:
        200:
          description: Ok
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A pocket with specified Id was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /pockets/{pocket_id}/edit_weight:
    put:
      tags:
        - "Pockets"
      operationId: editWeight
      summary: Edit the weight of weighed pockets from logged organization.
      parameters:
        - in: path
          name: pocket_id
          required: true
          type: integer
        - in: header
          name: ApiKey
          required: true
        - in: body
          name: weight
          required: true
          type: number
      responses:
        200:
          description: Ok
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A pocket with specified Id was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /pockets/{pocket_id}/edit_serial_number:
    put:
      tags:
        - "Pockets"
      operationId: editSerialNumber
      summary: Edit the serial number of a pocket from logged organization.
      parameters:
        - in: path
          name: pocket_id
          required: true
          type: integer
        - in: body
          name: serial_number
          required: true
          type: string
      responses:
        200:
          description: Ok
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A pocket with specified Id was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /containers:
    get:
      tags:
        - "Containers"
      operationId: getContainers
      summary: List available containers from logged organization.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Container'
          headers:
            Link:
              schema:
                type: string
              description: gives the information of last, next, previous or first page.
            Per-page:
              schema:
                type: integer
              description: gives information of the number of records per page.
            Total:
              schema:
                type: integer
              description: gives the number of records in total.
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /containers/{container_id}:
    get:
      tags:
        - "Containers"
      operationId: getContainer
      summary: Get one container from logged organization.
      parameters:
        - in: path
          name: container_id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/WebContainer'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A container with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []
    put:
      tags:
        - "Containers"
      operationId: updateContainer
      summary: Update the status of a container from logged organization.
      parameters:
        - in: path
          name: container_id
          required: true
          type: integer
        - in: body
          name: container
          schema:
            $ref: '#/definitions/Container'
      responses:
        200:
          description: Ok
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A container with specified Id was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /routes:
    get:
      tags:
        - "Routes"
      operationId: listingRoutes
      summary: Listing all the routes from the organization.
      parameters:
        - in: query
          name: page
          type: integer
        - in: query
          name: per_page
          type: integer
        - in: query
          name: init_date
          required: false
          type: string
          format: date
        - in: query
          name: end_date
          required: false
          type: string
          format: date
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Create_route'
          headers:
            Link:
              schema:
                type: string
              description: gives the information of last, next, previous or first page.
            Per-page:
              schema:
                type: integer
              description: gives information of the number of records per page.
            Total:
              schema:
                type: integer
              description: gives the number of records in total.
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []
    post:
      tags:
        - "Routes"
      operationId: createRoute
      summary: Create a route belonging to logged organization.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Create_route'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /routes/{route_id}:
    get:
      tags:
        - "Routes"
      operationId: getRoute
      summary: Show a route from logged organization.
      parameters:
        - in: path
          name: route_id
          required: true
          type: integer
      responses:
        200:
          description: OK
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A route with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []
    put:
        tags:
          - "Routes"
        operationId: endRoute
        summary: End a route from logged organization.
        parameters:
          - in: path
            name: route_id
            required: true
            type: integer
          - in: body
            name: route
            schema:
              $ref: '#/definitions/Route'
        responses:
          200:
            description: OK
          400:
            description: Malformed request.
            schema:
              $ref: '#/definitions/Error'
          401:
            description: Unauthorized request.
            schema:
              $ref: '#/definitions/Error'
          404:
            description: A route with the specified ID was not found.
            schema:
              $ref: '#/definitions/Error'
          500:
            description: Unexpected error.
            schema:
              $ref: '#/definitions/Error'
        security:
          - ApiKey: []

  /routes/{route_id}/events:
    post:
      tags:
        - "Events"
      operationId: createEvent
      summary: Add a collection to a route and creates an event and pockets for that collection.
      parameters:
        - in: path
          name: route_id
          required: true
          type: integer
        - in: body
          name: event
          schema:
            $ref: '#/definitions/Event'
        - in: body
          name: collection
          schema:
            $ref: '#/definitions/EventCollection'
      responses:
        200:
          description: OK
        400:
          description: An attribute is missing.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A route with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /routes/{route_id}/collections:
    post:
      tags:
        - "Collections"
      operationId: createCollection
      summary: Add a collection to a route, associate it to a container and add pockets to created collection.
      parameters:
        - in: path
          name: route_id
          required: true
          type: integer
        - in: body
          name: collection
          schema:
            $ref: '#/definitions/Collection'
      responses:
        200:
          description: OK
        400:
          description: A container with specified Id was not found.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: A route with the specified ID was not found.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /classification:
    post:
      tags:
        - "Classification"
      operationId: classifyPockets
      summary: Classify a list of pockets from logged organization.
      parameters:
        - in: body
          schema:
            $ref: '#/definitions/Classification'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ClassifiedPocket'
        400:
          description: Malformed request.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

  /questions:
    get:
      tags:
        - "Questions"
      operationId: getQuestions
      summary: Get six random questions.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Question'
        401:
          description: Unauthorized request.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
      security:
        - ApiKey: []

definitions:
  Organization:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
    required:
      - id
      - name
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
      ci:
        type: string
      email:
        type: string
    required:
      - id
      - name
      - surname
      - ci
      - email
  Bale:
    type: object
    required:
      - weight
      - material
    properties:
      weight:
        type: number
      material:
        type: string
        enum:
          - Trash
          - Glass
          - Plastic
    example:
      weight: 13.7
      material: Glass
  UnclassifiedPocket:
    type: object
    properties:
      id:
        type: integer
      serial_number:
        type: string
      weight:
        type: float
      state:
        enum:
        - "Unweighed"
        - "Weighed"
  ClassifiedPocket:
    type: object
    properties:
      id:
        type: integer
      serial_number:
        type: string
      weight:
        type: float
      state:
        enum:
        - "Classified"
      kg_trash:
        type: number
      kg_recycled_plastic:
        type: number
      kg_recycled_glass:
        type: number
  Container:
      type: object
      required:
        - status
      properties:
        id:
          type: integer
        latitude:
          type: string
        longitude:
          type: string
        status:
          type: string
          enum:
            - Ok
            - Damaged
      example:
        id: 5
        latitude: '-13.843669'
        longitude: '-60.894236'
        status: Ok
  WebContainer:
      type: object
      required:
        - status
      properties:
        id:
          type: integer
        latitude:
          type: string
        longitude:
          type: string
        status:
          type: string
          enum:
            - Ok
            - Damaged
        kg_trash:
          type: number
        kg_recycled_plastic:
          type: number
        kg_recycled_glass:
          type: number
      example:
        id: 5
        latitude: '-13.843669'
        longitude: '-60.894236'
        status: Ok
        kg_trash: 120
        kg_recycled_plastic: 20.8
        kg_recycled_glass: 50
  Collection:
    type: object
    required:
      - collection_point_id
      - pockets_attributes
    properties:
      collection_point_id:
        type: integer
      pockets_attributes:
        type: array
        items:
          type: object
          properties:
            serial_number:
              type: string
    example:
      collection_point_id: 1
      pocket_attributes: [{"serial_number": "B05"},
                          {"serial_number": "B18"}]
  EventCollection:
    type: object
    required:
      - pockets_attributes
    properties:
      pockets_attributes:
        type: array
        items:
          type: object
          properties:
            serial_number:
              type: string
    example:
      pocket_attributes: [{"serial_number": "B05"},
                          {"serial_number": "B18"}]
  Event:
    type: object
    required:
      - latitude
      - longitude
      - description
    properties:
      latitude:
        type: string
      longitude:
        type: string
      description:
        type: string
    example:
      latitude: '-13.843669'
      longitude: '-60.894236'
      description: 'School festival'
  Route:
      type: object
      required:
        - length
        - points
      properties:
        length:
          type: number
        points:
          type: array
          items:
            type: array
            items:
              type: number
      example:
        length: 17.5
        points: [[1,2],[3,4],[5,6]]
  Create_route:
    type: object
    properties:
      id:
        type: integer
      length:
        type: number
      created_at:
        type: string
      user:
        schema:
          $ref: '#/definitions/User'
      pockets:
        type: array
        items:
          type: object
          properties:
            serial_number:
              type: string
    example:
      id: 6
      length: nil
      created_at: "2018-10-27 19:16:25 UTC"
      user: {
        id: 1,
        name: "Federico",
        surname: "Balarini",
        email: "bala@email.com",
        ci: "12345678"
      }
      pockets: []
  Classification:
    type: object
    properties:
      kg_trash:
        type: number
      kg_plastic:
        type: number
      kg_glass:
        type: number
      pocket_ids:
        type: array
        items:
          integer
    example:
      kg_trash: 120
      kg_plastic: 20.8
      kg_glass: 50
      pocket_ids: [1,3,5]
  Error:
    type: object
    properties:
      http_status:
        type: "integer"
      description:
        type: string
      details:
        type: string
  Question:
    type: object
    properties:
      id:
        type: "integer"
      question:
        type: string
      option_a:
        type: string
      option_b:
        type: string
      option_c:
        type: string
      option_d:
        type: string
      correct_option:
        type: string
